name = "taillogger"
main = "src/main.ts"
compatibility_date = "2026-08-20"
send_metrics = false
minify = true
upload_source_maps = true
preview_urls = false
workers_dev = false

[secrets]
required = ["WEBHOOK"]

[[kv_namespaces]]
binding = "LOG_SETTINGS"
id = "939b548639af4122907b6582dd3ab81d"

[vars]
DEFAULT_LOG_LEVEL = "log"
# max is 20
MAX_FIELDS = "8"

# if we should be internally logging the tail system's activity
LOG_INTERNAL_ACTIVITY = "false"