name = "taillogger"
main = "src/main.ts"
compatibility_date = "2026-08-20"
send_metrics = false
minify = true
upload_source_maps = true
preview_urls = false
workers_dev = false

[secrets]
required = ["WEBHOOK"]

[vars]
LOG_LEVEL = "warn"
# max is 20
MAX_FIELDS = "8"

# if we should be internally logging the tail system's activity
LOG_INTERNAL_ACTIVITY = "false"